# Dependabot configuration for Brixie
# Automatically updates dependencies across all platforms

version: 2
updates:

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "mpwg"
    labels:
      - "dependencies"
      - "flutter"
    commit-message:
      prefix: "flutter"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "mpwg"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      setup-actions:
        patterns:
          - "actions/setup-*"
          - "actions/checkout*"
      build-actions:
        patterns:
          - "actions/upload-*"
          - "actions/download-*"
          - "actions/cache*"
      security-actions:
        patterns:
          - "*security*"
          - "*codeql*"
          - "*trivy*"